services:
  garage:
    build:
      dockerfile: Dockerfile
    volumes:
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
    environment:
      GARAGE_ACCESS_KEY_ID: GKddad3c4f703b0198c28afc13
      GARAGE_SECRET_ACCESS_KEY: 08e1d8f6dca7c0411ffc321243d282ca40915e585698235d4aa4426749290389
      GARAGE_BUCKETS: static:public,media:public,upload

volumes:
  garage-meta:
  garage-data:
