services:
  garage:
    build:
      dockerfile: Dockerfile
      args:
        GARAGE_VERSION: ${GARAGE_VERSION}
        RUST_VERSION: ${RUST_VERSION}
    volumes:
      - garage-meta:/var/lib/garage/meta
      - garage-data:/var/lib/garage/data
    env_file:
      - example.env

volumes:
  garage-meta:
  garage-data:
